apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{APP}}-{{COLOR}}
  labels:
    app: {{APP}}
    color: {{COLOR}}
spec:
  replicas: {{REPLICAS}}
  selector:
    matchLabels:
      app: {{APP}}
      color: {{COLOR}}
  template:
    metadata:
      labels:
        app: {{APP}}
        color: {{COLOR}}
    spec:
      containers:
      - name: {{APP}}
        image: {{IMAGE}}
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
